### ISSUE TITLE
Create a unified default dashboard

### ISSUE THREAD

**Issue by willcl-ark** [bitcoin-dev-project/warnet#388] opened 2024-06-28 09:16 UTC
- Doesn't need login, multiple users etc.
- Can just provide jump-links to logging, graphing, etc. pages

**Comment by josibake** [comment] 2024-09-02 11:40
possibly duplicate of #437 ? adding Tabconf milestone for now,  because this could be a solution for displaying wargame results.

**Comment by pinheadmz** [comment] 2024-09-03 14:36
closing as duplicate of #437 , this issue was opened pre-pasta/helm i think we can clean it up

**Closed as completed by pinheadmz** 2024-09-03 14:36 UTC
